name: Lint
on:
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 10m
      - name: Check go.mod
        env:
          CI: false
        run: |
          go mod tidy
          cd hack/migrate
          go mod tidy
          changed_files=$(git status -s)
          [[ -z "$changed_files" ]] ||  (printf "Change is detected in: \n$changed_files\n Did you run 'go mod tidy' before sending the PR?" && exit 1)
